export enum Code39BarWidth {
    NARROW,
    WIDE,
}

export const Code39BarEncoding: Record<string, Code39BarWidth[]> = {
    '0': [Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW],
    '1': [Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE],
    '2': [Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE],
    '3': [Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW],
    '4': [Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE],
    '5': [Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW],
    '6': [Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW],
    '7': [Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.WIDE],
    '8': [Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW],
    '9': [Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW],
    'A': [Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE],
    'B': [Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE],
    'C': [Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW],
    'D': [Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE],
    'E': [Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW],
    'F': [Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW],
    'G': [Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.WIDE],
    'H': [Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW],
    'I': [Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW],
    'J': [Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW],
    'K': [Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE],
    'L': [Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE],
    'M': [Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW],
    'N': [Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE],
    'O': [Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW],
    'P': [Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW],
    'Q': [Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.WIDE],
    'R': [Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW],
    'S': [Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW],
    'T': [Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW],
    'U': [Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE],
    'V': [Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE],
    'W': [Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW],
    'X': [Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE],
    'Y': [Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW],
    'Z': [Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW],
    '-': [Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.WIDE],
    '.': [Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW],
    ' ': [Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW],
    '$': [Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW],
    '/': [Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW],
    '+': [Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW],
    '%': [Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW],
    '*': [Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.WIDE, Code39BarWidth.NARROW, Code39BarWidth.NARROW],
}