export enum BarWidth {
    NARROW,
    WIDE,
}

export const BarEncoding: Record<string, BarWidth[]> = {
    '0': [BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW],
    '1': [BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE],
    '2': [BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE],
    '3': [BarWidth.WIDE, BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW],
    '4': [BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE],
    '5': [BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW],
    '6': [BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW],
    '7': [BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.WIDE],
    '8': [BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW],
    '9': [BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW],
    'A': [BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE],
    'B': [BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE],
    'C': [BarWidth.WIDE, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW],
    'D': [BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE],
    'E': [BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW],
    'F': [BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW],
    'G': [BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW, BarWidth.WIDE],
    'H': [BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW],
    'I': [BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW],
    'J': [BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW],
    'K': [BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE],
    'L': [BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE],
    'M': [BarWidth.WIDE, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW],
    'N': [BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE],
    'O': [BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW],
    'P': [BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW],
    'Q': [BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE, BarWidth.WIDE],
    'R': [BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW],
    'S': [BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW],
    'T': [BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW],
    'U': [BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE],
    'V': [BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE],
    'W': [BarWidth.WIDE, BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW],
    'X': [BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE],
    'Y': [BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW],
    'Z': [BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW],
    '-': [BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.WIDE],
    '.': [BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW],
    ' ': [BarWidth.NARROW, BarWidth.WIDE, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW],
    '$': [BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW],
    '/': [BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW],
    '+': [BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW],
    '%': [BarWidth.NARROW, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW],
    '*': [BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.WIDE, BarWidth.NARROW, BarWidth.NARROW],
}